# Generated by Django 5.0.4 on 2024-05-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
